title: My friends
author: Fahad Bin Hussain
email: fahadbinhussain@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, everyone, Fahad here! Today, I am going to introduce you to my friends, Dipu & Shajib.
theme: minima


# social links
twitter_username: FahadBinHussai_ # DO NOT include the @ character, or else the build will fail!
github_username:  FahadBinHussain # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
